### PR TITLE
github: test for solutions on push/pr

### PR DESCRIPTION
**Pull request by lsf37**
This adds a GitHub action for testing tutorial solutions. Uses seL4/ci-actions#126

### CODE REVIEW

**Comment by lsf37** [comment]
The "links" check fails for unrelated reasons (D61 downloads don't really work any more)

**Comment by kent-mcleod** [comment]
@lsf37, while you're here, do you think you can get the camke-vm-linux and camkes-vm-cross tutorials running in CI?

**Comment by lsf37** [comment]
> @lsf37, while you're here, do you think you can get the camkes-vm-linux and camkes-vm-cross tutorials running in CI?

I can give it a shot.

**Comment by lsf37** [comment]
(switched to the master branch action)

I'll merge this one for now, and we can see if there is anything to be done about the VM tests. It looks like qemu can't simulate VT-x without host support, and we can't pass that through on GitHub, but maybe there is another option.

**Review by Xaphiosis — APPROVED** [review]

**Pull request merged**
