### PR TITLE
docsite/tutorial python fixes

### PR DESCRIPTION
**Pull request by lsf37**
The docsite is not building any more, because jinja2 >= version 3.1 has removed `contextfilter` and `contextfunction` (replaced by `pass_context`).

### CODE REVIEW

**Comment by kent-mcleod** [comment]
Will this still work with the older versions of jinja2?

**Comment by lsf37** [comment]
> Will this still work with the older versions of jinja2?

The new one was introduced in version 3.0 (and the old ones deprecated), the old one was removed in 3.1. It won't work with versions older than 3.0, but since this is coming from pip anyway, I don't see problems on older Linux distributions or similar.

**Comment by kent-mcleod** [comment]
It might be necessary to update the sel4-deps to require jinja >= 3.0 then.  Otherwise people that have already installed the dependency before 3.0 will see old versions. My machine has 2.11 and 2.11.x was last updated 16 days ago (the last maintenance update though).

**Comment by lsf37** [comment]
Good point. We could also require an older version, but it's going to make life harder for people who do need newer features. Ok, so I should update sel4-deps concurrently.

**Comment by lsf37** [comment]
https://github.com/seL4/camkes-tool/pull/107 now sets a minimum version.

**Pull request merged**
