### PR TITLE
Foundation setup and SPDX tags

### PR DESCRIPTION
**Pull request by lsf37**
This does slightly more than some of the other SPDX pull requests: I've turned template comment headers into markdown comments for the tutorials, so that GitHub doesn't render all of the copyright headers as multiple `h1` headlines.

As far as I can see, this should be fine, but I haven't regenerated anything with it yet.

### CODE REVIEW

**Comment by lsf37** [comment]
@kent-mcleod I'm not entirely sure about what I did with those template comments.

Alternatively, we could also make `<!--` and `-->` template comments, which would make `template.py` treat the copyright headers as template headers again. There is one further comment in the files that would have to be updated, but that's it.

**Review by nomadeel — APPROVED** [review]

**Comment by nomadeel** [comment]
What you did for the various tutorial templates looks good to me. As long as they don't show up on the tutorials themselves when we generate the pages, it's fine.

Kent may have other opinions though.

**Review by oliver-wm — APPROVED** [review]

**Comment by oliver-wm** [comment]
I'm happy to merge this unless you want to wait for @kent-mcleod

**Comment by lsf37** [comment]
Let's merge it, and fix if something unexpected does turn out to happen.

**Pull request merged**
